# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file './mgf_qt_ui/ui_xml/mgf_main.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setEnabled(True)
        MainWindow.resize(600, 400)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setMinimumSize(QtCore.QSize(600, 400))
        MainWindow.setMaximumSize(QtCore.QSize(600, 400))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setBold(False)
        font.setWeight(50)
        MainWindow.setFont(font)
        MainWindow.setAccessibleName("")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setGeometry(QtCore.QRect(9, 9, 581, 381))
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.frame)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(0, 70, 251, 291))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.verticalLayoutWidget)
        self.gridLayout.setSizeConstraint(QtWidgets.QLayout.SetMinimumSize)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.textBrowser = QtWidgets.QTextBrowser(self.verticalLayoutWidget)
        self.textBrowser.setEnabled(True)
        self.textBrowser.setTabChangesFocus(True)
        self.textBrowser.setUndoRedoEnabled(True)
        self.textBrowser.setOpenExternalLinks(True)
        self.textBrowser.setObjectName("textBrowser")
        self.gridLayout.addWidget(self.textBrowser, 1, 0, 1, 1)
        self.label_out = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_out.setEnabled(True)
        self.label_out.setAlignment(QtCore.Qt.AlignCenter)
        self.label_out.setObjectName("label_out")
        self.gridLayout.addWidget(self.label_out, 0, 0, 1, 1)
        self.gridLayoutWidget = QtWidgets.QWidget(self.frame)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(279, 9, 301, 351))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.horizontalLayoutWidget = QtWidgets.QWidget(self.frame)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(450, 360, 131, 22))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout_github = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout_github.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_github.setObjectName("horizontalLayout_github")
        self.label = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.label.setMaximumSize(QtCore.QSize(100, 20))
        self.label.setTextFormat(QtCore.Qt.MarkdownText)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setOpenExternalLinks(True)
        self.label.setObjectName("label")
        self.horizontalLayout_github.addWidget(self.label)
        self.horizontalLayoutWidget_2 = QtWidgets.QWidget(self.frame)
        self.horizontalLayoutWidget_2.setGeometry(QtCore.QRect(0, 10, 251, 51))
        self.horizontalLayoutWidget_2.setObjectName("horizontalLayoutWidget_2")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.horizontalLayoutWidget_2)
        self.gridLayout_3.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.lineEdit_ver1 = QtWidgets.QLineEdit(self.horizontalLayoutWidget_2)
        self.lineEdit_ver1.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_ver1.setObjectName("lineEdit_ver1")
        self.gridLayout_3.addWidget(self.lineEdit_ver1, 1, 0, 1, 1)
        self.lineEdit_ver2 = QtWidgets.QLineEdit(self.horizontalLayoutWidget_2)
        self.lineEdit_ver2.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_ver2.setObjectName("lineEdit_ver2")
        self.gridLayout_3.addWidget(self.lineEdit_ver2, 1, 1, 1, 1)
        self.lineEdit_ver3 = QtWidgets.QLineEdit(self.horizontalLayoutWidget_2)
        self.lineEdit_ver3.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_ver3.setObjectName("lineEdit_ver3")
        self.gridLayout_3.addWidget(self.lineEdit_ver3, 1, 2, 1, 1)
        self.label_ver = QtWidgets.QLabel(self.horizontalLayoutWidget_2)
        self.label_ver.setAlignment(QtCore.Qt.AlignCenter)
        self.label_ver.setObjectName("label_ver")
        self.gridLayout_3.addWidget(self.label_ver, 0, 0, 1, 3)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MinecraftGetForge"))
        MainWindow.setWhatsThis(_translate("MainWindow", "版本"))
        self.textBrowser.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'微软雅黑\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.label_out.setText(_translate("MainWindow", "Forge列表"))
        self.label.setText(_translate("MainWindow", "<html><head/><body><p><a href=\"https://github.com/Trisuborn/MinecraftGetForge\"><span style=\" text-decoration: underline; color:#0000ff;\">项目GitHub页</span></a></p></body></html>"))
        self.lineEdit_ver1.setPlaceholderText(_translate("MainWindow", "1"))
        self.lineEdit_ver2.setPlaceholderText(_translate("MainWindow", "12"))
        self.lineEdit_ver3.setPlaceholderText(_translate("MainWindow", "2"))
        self.label_ver.setText(_translate("MainWindow", "版本"))
